config/routes.rb
Rails.application.routes.draw do
    scope module: :public do
      root to: 'homes#top'
      get '/about' => 'homes#about'
      
      #顧客のページ関連
      get '/customers/my_page' => 'customers#show'
      get '/customers/infomation/edit' => 'customers#edit'
      patch '/customers/infomation/up_date' => 'customers#update'
      get '/customers/unsubscribe' => 'customers#unsubscribe'
      patch '/customers/withdraw' => 'customers#withdraw'
      
      #商品関連
      resources :items, only: [:index, :show]
      
      #注文関連
      post '/orders/comfirm' => 'orders#comfirm'
      get '/orders/complete' => 'orders#complete'
      post '/orders' => 'orders#create'
      resources :orders, only: [:new, :index, :show]
      
      #カート関連
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
      resources :cart_items, only: [:index, :update, :destroy, :create]
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    end
    
    #顧客情報関連
    devise_for :customers,skip: [:passwords], controllers: {
        registrations: "public/registrations",
        sessions: 'public/sessions'
    }
   
    
   #管理者情報関連
    devise_for :admin, skip:[:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }
    
    namespace :admin do
      get '/' => 'homes#top'
      resources :items, only: [:new, :create, :index, :show, :edit, :update]
      resources :genres, only: [:index, :edit, :create, :update]
      resources :customers, only: [:index, :show, :edit, :update]
      patch '/customers' => 'customer#update'
      resources :orders, only: [:show, :update]
      patch '/order_details' => 'order#update'
    end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 has_many :cart_items, dependent: :destroy
 has_many :orders, dependent: :destroy
 has_many :addresses, dependent: :destroy
 
  validates :encrypted_password, presence: true
  validates :email, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, 
    :first_name_kana, :is_deleted, :telephone_number, :postal_code, :address,
    :email, :password)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = current_customer
  end
  
  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customers_my_page_path
  end

  def edit
    @customer = current_customer
  end
  
  def withdraw
    @customer = current_customer
    @customer.update!(is_deleted: true)
    redirect_to root_path
  end

  def unsubscribe
  end
 
 private
  def customer_params
    params.permit(:last_name, :first_name, :last_name_kana, 
    :first_name_kana, :telephone_number, :postal_code, :address,
    :email, :password)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<h1>会員情報編集</h1>
<%= form_with model: @customer, url: customers_infomation_up_date_path, method: :patch do |f| %>
  <div class="field">
    <%= f.label :email %>アドレス<br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>
  
  <div class="field">
    <%= f.label :last_name %>苗字<br>
    <%= f.text_field :last_name %>
  </div>
  
  <div class="field">
    <%= f.label :first_name %>名前<br>
    <%= f.text_field :first_name %>
  </div>
  
  <div class="field">
    <%= f.label :last_name_kana %>苗字カナ<br>
    <%= f.text_field :last_name_kana %>
  </div>
  
  <div class="field">
    <%= f.label :first_name_kana %>名前カナ<br>
    <%= f.text_field :first_name_kana %>
  </div>
  
  <div class="field">
    <%= f.label :postal_code %>郵便番号<br>
    <%= f.text_field :postal_code %>
  </div>
  
  <div class="field">
    <%= f.label :address %>住所<br>
    <%= f.text_field :address %>
  </div>
  
  <div class="field">
    <%= f.label :telephone_number %>電話番号<br>
    <%= f.text_field :telephone_number %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>
    <%= f.submit "変更を保存" %>
    <%= link_to "退会する", customers_unsubscribe_path %>
<% end %>

app/views/customers/show.html.erb
<div>
    <h1>マイページ</h1>
<p><strong>登録情報</strong><%= link_to "編集する", customers_infomation_edit_path %></p>
    <h4>氏名</h4><%= current_customer.last_name %> <%= current_customer.first_name %><br>
                 <%= current_customer.last_name_kana %> <%= current_customer.first_name_kana %><br>
    <h4>住所</h4><%= current_customer.postal_code %><br><%= current_customer.address %><br>
    <h4>電話番号</h4><%= current_customer.telephone_number %>
</div>

<h3>配送先</h3><%= link_to "お届け先一覧", addresses_index_path %>

app/views/customers/unsubscribe.html.erb
<h3>本当に退会しますか？</h3>
<p>退会すると、会員情報や<br>これまでの購入履歴が閲覧できなくなります。<br>
退会する場合は、「退会する」をクリックしてください。</p>

<%= link_to "退会しない", customers_infomation_edit_path %>
<%= link_to "退会する", customers_withdraw_path, method: :patch %>