config/routes.rb
Rails.application.routes.draw do
    scope module: :public do
      root to: 'homes#top'
      get '/about' => 'homes#about'
      
      #顧客のページ関連
      get '/customers/my_page' => 'customers#show'
      get '/customers/infomation/edit' => 'customers#edit'
      patch '/customers/infomation/up_date' => 'customers#update'
      get '/customers/unsubscribe' => 'customers#unsubscribe'
      patch '/customers/withdraw' => 'customers#withdraw'
      
      #商品関連
      resources :items, only: [:index, :show]
      
      #注文関連
      post '/orders/comfirm' => 'orders#comfirm'
      get '/orders/complete' => 'orders#complete'
      post '/orders' => 'orders#create'
      resources :orders, only: [:new, :index, :show]
      
      #カート関連
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
      resources :cart_items, only: [:index, :update, :destroy, :create]
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    end
    
    #顧客情報関連
    devise_for :customers,skip: [:passwords], controllers: {
        registrations: "public/registrations",
        sessions: 'public/sessions'
    }
   
    
   #管理者情報関連
    devise_for :admin, skip:[:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }
    
    namespace :admin do
      get '/' => 'homes#top'
      resources :items, only: [:new, :create, :index, :show, :edit, :update]
      resources :genres, only: [:index, :edit, :create, :update]
      resources :customers, only: [:index, :show, :edit, :update]
      patch '/customers' => 'customer#update'
      resources :orders, only: [:show, :update]
      patch '/order_details' => 'order#update'
    end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    
    has_one_attached :item_image
    
    def get_item_image(width, height)
        unless item_image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            item_image.attach(io:File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        item_image.variant(resize_to_limit: [width, height]).processed
    end
    #小計を求めるメソッド
    def subtotal
        item.with_tax_price * amount
    end
    
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
 
  def index
    @cart_items = CartItem.all
    @items = Item.all
    @cart_item = @items.all
    #合計金額の初期値は0円
    @total = 0
  end
  
  
 def create
    @cart_item = CartItem.find_by(item_id: params[:cart_item][:item_id])
    if @cart_item
      #カートにitemが存在したらamountに新しいCart_itemのamountを足す
      @cart_item.amount += CartItem.new(cart_item_params).amount
    else
      #カートにitemが無ければ新しく作成する
      @cart_item = CartItem.new(cart_item_params)
    end
    #ログインcustomerのみ更新できるようにするため分岐の外に記述する
    if @cart_item.customer = current_customer
      @cart_item.save!
      redirect_to cart_items_path
    else
      redirect_to new_customer_session_path
    end
 end

  
  def update
    @cart_item = CartItem.find(params[:id])
    @item = Item.all
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end
  
  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy!
    redirect_to cart_items_path
  end
  
  def destroy_all
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end
  
  private
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<h1>ショッピングカート</h1>
    <%= link_to "カートを空にする", destroy_all_cart_items_path, method: :delete, "data-confirm" => "本当に空にしますか？" %><br>
<div>
    <table>
        <thead>
            <tr>
                <th></th>
                <th>商品名</th>
                <th>単価(税込)</th>
                <th>数量</th>
                <th></th>
                <th>小計</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @cart_items.each do |cart_item| %>
                <tr>
                    <td><%= image_tag cart_item.item.get_item_image(100,100) %></td>
                    <td><%= cart_item.item.name %></td>
                    <td><%= cart_item.item.with_tax_price %>円</td>
                    <td><%= cart_item.amount %>個</td>
                    <td>
                        <%= form_with model: @cart_items, url: cart_item_path(cart_item.id), method: :patch do |f| %>
                            <%= f.hidden_field :@cart_item, :value => cart_item.amount %>
                            <%= f.select :amount, *[1..10] %>
                        <%= f.submit "変更" %>
                        <% end %>
                    </td>
                    <td><%= cart_item.subtotal %>円</td>
                    <td><%= link_to "削除する", cart_item_path(cart_item.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
                </tr>
                <% @total += cart_item.subtotal %>
            <% end %>
        </tbody>
    </table>
    <p>合計金額（税込）<%= @total %>円</p>
    <%= link_to "買い物を続ける", items_path %><br>
    <%= link_to "会計する", new_order_path %><br>
</div>