config/routes.rb
Rails.application.routes.draw do
    scope module: :public do
      root to: 'homes#top'
      get '/about' => 'homes#about'
      
      #顧客のページ関連
      get '/customers/my_page' => 'customers#show'
      get '/customers/infomation/edit' => 'customers#edit'
      patch '/customers/infomation/up_date' => 'customers#update'
      get '/customers/unsubscribe' => 'customers#unsubscribe'
      patch '/customers/withdraw' => 'customers#withdraw'
      
      #商品関連
      resources :items, only: [:index, :show]
      
      #注文関連
      post '/orders/comfirm' => 'orders#comfirm'
      get '/orders/complete' => 'orders#complete'
      post '/orders' => 'orders#create'
      resources :orders, only: [:new, :index, :show]
      
      #カート関連
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
      resources :cart_items, only: [:index, :update, :destroy, :create]
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    end
    
    #顧客情報関連
    devise_for :customers,skip: [:passwords], controllers: {
        registrations: "public/registrations",
        sessions: 'public/sessions'
    }
   
    
   #管理者情報関連
    devise_for :admin, skip:[:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }
    
    namespace :admin do
      get '/' => 'homes#top'
      resources :items, only: [:new, :create, :index, :show, :edit, :update]
      resources :genres, only: [:index, :edit, :create, :update]
      resources :customers, only: [:index, :show, :edit, :update]
      patch '/customers' => 'customer#update'
      resources :orders, only: [:show, :update]
      patch '/order_details' => 'order#update'
    end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/item.rb
class Item < ApplicationRecord
    #商品画像
    has_one_attached :item_image
    
    has_many :order_details, dependent: :destroy
    has_many :cart_items, dependent: :destroy
    belongs_to :genre
   
    
    #消費税を求めるメソッド（10％
    def with_tax_price
        (item_price*1.1).floor
    end
    
    def get_item_image(width, height)
        unless item_image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            item_image.attach(io:File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        item_image.variant(resize_to_limit: [width, height]).processed
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
    @genres = Genre.all
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path
    else
      @genres = Genre.all
      render :new
    end
  end
  
  def index
    @items = Item.page(params[:page])
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end
  
  private 
  def item_params
    params.require(:item).permit(:name, :item_image, :introduction, :item_price, :genre_id)
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end
  
  def item_params
    params.require(:item).permit(
     :name, :item_image, :introduction, :item_price, :genre_id)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<p><strong>商品一覧</strong>（全<%= @items.count %>件）</p>
<% @items.each do |item| %>
    <div>
        <%= link_to item_path(item.id) do %>
            <%= image_tag item.get_item_image(100,100) %></p>
            <p>商品名:<%= item.name %></p>
        <% end %>
        <p>ジャンル名:<%= item.genre.name %></p>
        <p>価格（税抜）<%= item.item_price %>円</p>
    </div>
<% end %>

app/views/items/show.html.erb
<h1>販売商品詳細</h1>
<div>
    <%= image_tag @item.get_item_image(100,100) %></p>
    <h2><%= @item.name %></h2>
    <P><%= @item.introduction %></P>
    <p><%= @item.with_tax_price %>円 (税込)</p>
    <p>商品ジャンル名:<%= @item.genre.name %></p>
<%= form_with model: @cart_item, url: cart_items_path, method: :post do |f| %>
    <p>数量を選択</p>
    <%= f.hidden_field :item_id, :value => @item.id %>
    <%= f.select :amount, *[1..10] %>
    <%= f.submit "カートに入れる" %>
<% end %>
<% if @item.id == current_admin %>
    <p><%= link_to "商品を編集する", edit_admin_item_path(@item.id) %></p>
<% end %>
</div>