config/routes.rb
Rails.application.routes.draw do
    scope module: :public do
      root to: 'homes#top'
      get '/about' => 'homes#about'
      
      #顧客のページ関連
      get '/customers/my_page' => 'customers#show'
      get '/customers/infomation/edit' => 'customers#edit'
      patch '/customers/infomation/up_date' => 'customers#update'
      get '/customers/unsubscribe' => 'customers#unsubscribe'
      patch '/customers/withdraw' => 'customers#withdraw'
      
      #商品関連
      resources :items, only: [:index, :show]
      
      #注文関連
      post '/orders/comfirm' => 'orders#comfirm'
      get '/orders/complete' => 'orders#complete'
      post '/orders' => 'orders#create'
      resources :orders, only: [:new, :index, :show]
      
      #カート関連
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
      resources :cart_items, only: [:index, :update, :destroy, :create]
      resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    end
    
    #顧客情報関連
    devise_for :customers,skip: [:passwords], controllers: {
        registrations: "public/registrations",
        sessions: 'public/sessions'
    }
   
    
   #管理者情報関連
    devise_for :admin, skip:[:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
    }
    
    namespace :admin do
      get '/' => 'homes#top'
      resources :items, only: [:new, :create, :index, :show, :edit, :update]
      resources :genres, only: [:index, :edit, :create, :update]
      resources :customers, only: [:index, :show, :edit, :update]
      patch '/customers' => 'customer#update'
      resources :orders, only: [:show, :update]
      patch '/order_details' => 'order#update'
    end
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    belongs_to :order
    
    def address_display
        '〒' + postal_code + '' + address + '' + name
    end
    
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    
    has_one_attached :item_image
    
    def get_item_image(width, height)
        unless item_image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            item_image.attach(io:File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        item_image.variant(resize_to_limit: [width, height]).processed
    end
    #小計を求めるメソッド
    def subtotal
        item.with_tax_price * amount
    end
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
 has_many :cart_items, dependent: :destroy
 has_many :orders, dependent: :destroy
 has_many :addresses, dependent: :destroy
 
  validates :encrypted_password, presence: true
  validates :email, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/home.rb
class Home < ApplicationRecord
    
    has_many :orders, dependent: :destroy
    has_many :order_details, dependent: :destroy
    has_one_attached :item_image
    
    def get_item_image(width, height)
        unless item_image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            item_image.attach(io:File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        item_image.variant(resize_to_limit: [width, height]).processed
    end
end

app/models/item.rb
class Item < ApplicationRecord
    #商品画像
    has_one_attached :item_image
    
    has_many :order_details, dependent: :destroy
    has_many :cart_items, dependent: :destroy
    belongs_to :genre
   
    
    #消費税を求めるメソッド（10％
    def with_tax_price
        (item_price*1.1).floor
    end
    
    def get_item_image(width, height)
        unless item_image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            item_image.attach(io:File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        item_image.variant(resize_to_limit: [width, height]).processed
    end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :addresses, dependent: :destroy
    has_many :order_details, dependent: :destroy
    belongs_to :customer
    
    #validates :payment_method, presence: true
    #validates :delivery_method, presence: true
    
    has_one_attached :item_image
    
    
    def get_item_image(width, height)
        unless item_image.attached?
            file_path = Rails.root.join('app/assets/images/no_image.jpg')
            item_image.attach(io:File.open(file_path),filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        item_image.variant(resize_to_limit: [width, height]).processed
    end
    
    #0ならクレジット払い、1なら銀行振込
    enum payment_method: { credit_card: 0, transfer: 1 }
    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
 
  def index
    @cart_items = CartItem.all
    @items = Item.all
    @cart_item = @items.all
    #合計金額の初期値は0円
    @total = 0
  end
  
  
 def create
    @cart_item = CartItem.find_by(item_id: params[:cart_item][:item_id])
    if @cart_item
      #カートにitemが存在したらamountに新しいCart_itemのamountを足す
      @cart_item.amount += CartItem.new(cart_item_params).amount
    else
      #カートにitemが無ければ新しく作成する
      @cart_item = CartItem.new(cart_item_params)
    end
    #ログインcustomerのみ更新できるようにするため分岐の外に記述する
    if @cart_item.customer = current_customer
      @cart_item.save!
      redirect_to cart_items_path
    else
      redirect_to new_customer_session_path
    end
 end

  
  def update
    @cart_item = CartItem.find(params[:id])
    @item = Item.all
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end
  
  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy!
    redirect_to cart_items_path
  end
  
  def destroy_all
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end
  
  private
  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = current_customer
  end
  
  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customers_my_page_path
  end

  def edit
    @customer = current_customer
  end
  
  def withdraw
    @customer = current_customer
    @customer.update!(is_deleted: true)
    redirect_to root_path
  end

  def unsubscribe
  end
 
 private
  def customer_params
    params.permit(:last_name, :first_name, :last_name_kana, 
    :first_name_kana, :telephone_number, :postal_code, :address,
    :email, :password)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end
  
  def item_params
    params.require(:item).permit(
     :name, :item_image, :introduction, :item_price, :genre_id)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/_order.html.erb
<h3>
    <%= order.customer.last_name %><%= order.customer.first_name %>さんの注文履歴</h3>
<div>
    <table>
        <thead>
            <tr>
                <th>購入日時</th>
                <th>注文個数</th>
            </tr>
        </thead>
        <tbody>
    <% order_detail.each do |order_detail| %>
            <tr>
                <td>
                    <%= order_detail.created_at.strftime('%Y/%m/%d') %>
                </td>
                <td>
                    <%= order_detail.amount %>
                </td>
            </tr>
    <% end %>
        </tbody>
    </table>
</div>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>ながのケーキ</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm ">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <h3>ながのケーキ</h3>
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li class="nav-item btn btn-sm">
              <%= button_to "商品一覧", admin_items_path, method: :get %>
            </li>
            <li class="nav-item btn btn-sm">
              <%= button_to "会員一覧", admin_customers_path, method: :get %>
            </li>
            <li class="nav-item btn btn-sm">
              <%= button_to "注文履歴一覧", admin_path, method: :get %>
            </li>
            <li class="nav-item btn btn-sm">
              <%= button_to "ジャンル一覧", admin_genres_path, method: :get %>
            </li>
            <li class ="nav-item btn btn-sm">
              <%= button_to "ログアウト", destroy_admin_session_path, method: :delete %>
            </li>
          <% elsif customer_signed_in? %>
          <p>ようこそ<strong><%= current_customer.first_name %></strong>さん！</p>
            <li class="nav-item btn btn-sm">
              <%= button_to "マイページ", customers_my_page_path, method: :get %>
            </li>
            <li class="nav-item btn btn-sm">
            <%= button_to "商品一覧", items_path, method: :get %>
            </li>
            <li class="nav-item btn btn-sm">
              <%= button_to "カート", cart_items_path, method: :get %>
            </li>
            <li class="nav-item btn btn-sm">
              <%= button_to "ログアウト", destroy_customer_session_path, method: :delete %>
            </li>
          <% else %>
          <li class="nav-item btn btn-sm">
            <%= button_to "Aboute", about_path, method: :get %>
          </li>
          <li class="nav-item btn btn-sm">
            <%= button_to "商品一覧", items_path, method: :get %>
          </li>
          <li class="nav-item btn btn-sm">
            <%= button_to "新規登録", new_customer_registration_path, method: :get %>
          </li>
          <li class="nav-item btn btn-sm">
            <%= button_to "ログイン", new_customer_session_path, method: :get %>
          </li>
        </div>
      </nav>
          <% end %>
        </ul>
    </header>
    <main class="md=auto">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <footer class="footer">
      <div class="border-top" style="padding:50px;"></div>
      </div>
    </footer>
  </body>
</html>